=== TOOP4EU/toop-commons/toop-commons/src/main/resources/xsd/toop/TOOP_DataExchange.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema 
	xmlns:toop="http://toop.eu"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:udt="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2"
	targetNamespace="http://toop.eu"
	version="0.5"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">  
<!-- QUESTION: I added a  version attribute here; is this useful? -->

	<xsd:import
		namespace="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2"
		schemaLocation="../common/UBL-UnqualifiedDataTypes-2.1.xsd" />
	
	<!--alternative ROOT elements-->
	<xsd:element name="TOOP_DataRequest" type="toop:TOOP_DataRequestType"/>  
	<xsd:element name="TOOP_DataResponse" type="toop:TOOP_DataResponseType"/>  
	<!--in the future we can add a TOOP_DataError root here-->
	
	<!--************************** -->
	<!--COMMON elements start here -->
	<!--************************** -->
	
	<xsd:complexType name="DataConsumerType">
		<xsd:sequence>
			<xsd:element name="DCUniqueIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DCName" type="udt:TextType"/>
			<xsd:element name="DCElectronicAddressIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DCWebsite" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>  
			<xsd:element name="DCLegalAddress" type="toop:AddressType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataSubjectType">
		<xsd:sequence>
			<xsd:element name="DataSubjectTypeCode" type="udt:CodeType"/>
			<xsd:element name="LegalEntity" type="toop:LegalEntityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="NaturalPerson" type="toop:NaturalPersonType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataRequestAuthorizationType">
		<xsd:sequence>
			<xsd:element name="DataRequestConsentToken" type="udt:IdentifierType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataRequestType">
		<xsd:sequence>
			<xsd:element name="DataRequestIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DataRequestDomainCode" type="udt:CodeType"/>
			<xsd:element name="DataElementRequestIndicator" type="udt:IndicatorType"/>
			<xsd:element name="DocumentRequestIndicator" type="udt:IndicatorType"/>
			<xsd:element name="DocumentRequestTypeCode" type="udt:CodeType" minOccurs="0" maxOccurs="unbounded"/>  <!--QUESTION: why the 0..n cardinality?-->
			<xsd:element name="PreferredDocumentFileTypeCode" type="udt:CodeType"/>
			<xsd:element name="DataRequestPurpose" type="udt:TextType"/>
			<xsd:element name="DataElementRequest" type="toop:DataElementRequestType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="LegalEntityType">
		<xsd:sequence>
			<xsd:element name="LegalPersonUniqueIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="LegalName" type="udt:TextType"/>  <!--QUESTION: will this support multiple names in countries using them?-->
			<xsd:element name="VATRegistrationNumber" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="TaxReferenceNumber" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="BusinessCode" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/> <!--QUESTION: is the plural "BusinessCodes" in the specifications a typo, or should we include more than one BusinessCode here?-->
			<xsd:element name="LegalEntityIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/> 
			<xsd:element name="EORIIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="SEEDIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="StandardIndustrialClassification" type="toop:CodeType-FourDigits" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="AuthorisedRepresentativeIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>  
			<xsd:element name="LegalEntityLegalAddress" type="toop:AddressType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="NaturalPersonType">
		<xsd:sequence>
			<xsd:element name="PersonIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="FamilyName" type="udt:TextType"/> 
			<xsd:element name="FirstName" type="udt:TextType"/> 
			<xsd:element name="BirthDate" type="xsd:date"/> 
			<xsd:element name="BirthFamilyName" type="udt:TextType" minOccurs="0" maxOccurs="1"/> 
			<xsd:element name="BirthPlace" type="udt:TextType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="GenderCode" type="toop:GenderType" minOccurs="0" maxOccurs="1"/>   <!--TODO: use udt:CodeType with restrictions-->
			<xsd:element name="NaturalPersonLegalAddress" type="toop:AddressType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataElementRequestType">  <!--QUESTION: should we add a "mandatory" indicator for each DataElementRequest, so you know some data is mandatory and some is "nice to have"? -->
		<xsd:sequence>
			<xsd:element name="DataElementRequestIdentifier" type="udt:IdentifierType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality?-->
			<xsd:element name="DataConsumerSemanticMappingIndicator" type="udt:IndicatorType"/> <!--QUESTION: should we use "DC" instead of "Data Consumer" as we do elsewhere?-->
			<xsd:element name="DataConsumerConceptIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="unbounded"/>  <!--QUESTION: why the 0..n cardinality?-->
			<xsd:element name="DataConsumerConcept" type="udt:TextType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality?--> 
			<xsd:element name="DataConsumerConceptSyntaxPathURI" type="udt:IdentifierType" minOccurs="0" maxOccurs="unbounded"/>  <!--QUESTION: why the 0..n cardinality? Also: isn't there a specific type for URI's?-->
			<xsd:element name="ToopConcept" type="udt:TextType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality?--> 
			<xsd:element name="ToopConceptDefinition" type="udt:TextType" minOccurs="0" maxOccurs="unbounded"/>  <!--QUESTION: why the 0..n cardinality?-->
			<xsd:element name="ToopConceptURI" type="udt:IdentifierType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality?  Also: isn't there a specific type for URI's?--> 
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="AddressType">
		<xsd:sequence>
			<xsd:element name="AddressLine1" type="udt:TextType" minOccurs="0" maxOccurs="1"/> <!--QUESTION: the specifications say you can use multiple lines; is it better to create AddressLine1, Addressline2, Addressline3 as commonly used in other projects? Noone in Europe uses needs more than 3 lines -->
			<xsd:element name="AddressLine2" type="udt:TextType" minOccurs="0" maxOccurs="1"/> <!--QUESTION: the specifications say you can use multiple lines; is it better to create AddressLine1, Addressline2, Addressline3 as commonly used in other projects? Noone in Europe uses needs more than 3 lines -->
			<xsd:element name="AddressLine3" type="udt:TextType" minOccurs="0" maxOccurs="1"/> <!--QUESTION: the specifications say you can use multiple lines; is it better to create AddressLine1, Addressline2, Addressline3 as commonly used in other projects? Noone in Europe uses needs more than 3 lines -->
			<xsd:element name="StreetName" type="udt:TextType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="StreetNumber" type="udt:TextType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="City" type="udt:TextType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="PostCode" type="udt:TextType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Country" type="udt:TextType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="CountryCode" type="toop:CodeType-TwoUppercaseLetters"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<!--************************** -->
	<!--COMMON elements stop here -->
	<!--************************** -->
	
	<!--************************************ -->
	<!--REQUEST specific elements start here -->
	<!--************************************ -->
	
	<!--note: TOOP_DataRequestType and TOOP_DateResponseType have many Elements in common, but these are repeated here for human readability-->
	<xsd:complexType name="TOOP_DataRequestType">
		<xsd:sequence>
			<xsd:element name="DocumentIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="DocumentIssueDate" type="xsd:date"/>
			<xsd:element name="DocumentIssueTime" type="xsd:time" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="DocumentUniversalUniqueIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DocumentVersionIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="CopyIndicator" type="udt:IndicatorType"/>
			<xsd:element name="DocumentTypeCode" type="toop:DocumentTypeCodeType"/>
			<xsd:element name="SpecificationIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="ProcessIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="SessionIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="DataConsumer" type="toop:DataConsumerType"/>
			<xsd:element name="DataSubject" type="toop:DataSubjectType"/>
			<xsd:element name="DataRequestAuthorization" type="toop:DataRequestAuthorizationType"/>
			<xsd:element name="DataRequest" type="toop:DataRequestType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<!--*********************************** -->
	<!--REQUEST specific elements stop here -->
	<!--*********************************** -->
	
	<!--************************************* -->
	<!--RESPONSE specific elements start here -->
	<!--************************************* -->
	
	<!--note: TOOP_DateResponseType and TOOP_DataRequestType have many Elements in common, but these are repeated here for human readability-->
	<xsd:complexType name="TOOP_DataResponseType">
		<xsd:sequence>
			<xsd:element name="DocumentIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="DocumentIssueDate" type="xsd:date"/>
			<xsd:element name="DocumentIssueTime" type="xsd:time" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="DocumentUniversalUniqueIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DocumentVersionIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="CopyIndicator" type="udt:IndicatorType"/>
			<xsd:element name="DocumentTypeCode" type="toop:DocumentTypeCodeType"/>
			<xsd:element name="SpecificationIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="ProcessIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="SessionIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="DataConsumer" type="toop:DataConsumerType"/>
			<xsd:element name="DataSubject" type="toop:DataSubjectType"/>
			<xsd:element name="DataRequestAuthorization" type="toop:DataRequestAuthorizationType"/>
			<xsd:element name="DataRequestIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DataRequest" type="toop:DataRequestType"/>
			<xsd:element name="DataResponse" type="toop:DataResponseType"/>
			<xsd:element name="DocumentResponse" type="toop:DocumentResponseType"/>
			<xsd:element name="DataProvider" type="toop:DataProviderType"/>
			<xsd:element name="NationalOOPServiceProvider" type="toop:NationalOOPServiceProviderType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataResponseType">
		<xsd:sequence>
			<xsd:element name="DataRequestIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DataResponseIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DataProviderSyntaxNameCode" type="udt:CodeType"/>
			<xsd:element name="DataResponseConfidentialityLevelCode" type="udt:CodeType"/>
			<xsd:element name="DataElementResponse" type="toop:DataElementResponseType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataElementResponseType"> 
		<xsd:sequence>
			<xsd:element name="DataElementRequestIdentifier" type="udt:IdentifierType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality?-->
			<xsd:element name="DataProviderSemanticMappingIndicator" type="udt:IndicatorType"/> <!--QUESTION: should we use "DC" instead of "Data Consumer" as we do elsewhere?-->
			<!--QUESTION: don't we need a "DataProviderConceptIdentifier" for simmetry, here? -->
			<xsd:element name="DataProviderConcept" type="udt:TextType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality?--> 
			<xsd:element name="DataProviderConceptSyntaxPathURI" type="udt:IdentifierType" minOccurs="0" maxOccurs="unbounded"/>  <!--QUESTION: why the 0..n cardinality? Also: isn't there a specific type for URI's?-->
			<xsd:element name="ResponseValueIdentifier" type="udt:IdentifierType" minOccurs="1" maxOccurs="unbounded"/>
			<xsd:element name="DataElementResponseValue" type="toop:DataElementResponseValueType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataElementResponseValueType">
		<xsd:sequence>
			<xsd:element name="ResponseValueIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="ResponseCodeIndicator" type="udt:IndicatorType"/>
			<!--TODO: add a "switch" construct here for the response type? -->
			<xsd:element name="ResponseErrorCode" type="udt:CodeType"/>
			<xsd:element name="ResponseIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="ResponseDescription" type="udt:TextType"/>
			<xsd:element name="ResponseAmount" type="udt:AmountType"/>
			<xsd:element name="ResponseCode" type="udt:CodeType"/>
			<xsd:element name="ResponseDate" type="xsd:date"/>  <!--QUESTION: should we use standard XSD dates and timestamps or UBL dates?-->
			<xsd:element name="ResponseIndicator" type="udt:IndicatorType"/>
			<xsd:element name="ResponseMeasure" type="udt:MeasureType"/>
			<xsd:element name="ResponseNumeric" type="udt:NumericType"/>
			<xsd:element name="ResponseQuantity" type="udt:QuantityType"/>
			<xsd:element name="ResponseTime" type="xsd:time"/>
			<xsd:element name="ResponseURI" type="udt:IndicatorType"/> 
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DocumentResponseType"> 
		<xsd:sequence>
			<xsd:element name="DocumentIdentifier" type="udt:IdentifierType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality? Also: the specs say it is an Indicator, but I guess it's a typo-->
			<xsd:element name="DocumentTypeCode" type="udt:CodeType" minOccurs="1" maxOccurs="unbounded"/> <!--QUESTION: why the 1..n cardinality?--> 
			<xsd:element name="DocumentName" type="udt:TextType" minOccurs="1" maxOccurs="unbounded"/>  <!--QUESTION: why the 1..n cardinality?--> 
			<xsd:element name="DocumentDescription" type="udt:TextType" minOccurs="0" maxOccurs="unbounded"/>  <!--QUESTION: why the 0..n cardinality? Also: isn't there a specific type for URI's?-->
			<xsd:element name="DocumentValidityPeriod" type="udt:TextType" minOccurs="0" maxOccurs="unbounded"/>  <!--QUESTION: why the 0..n cardinality? Also: why is this a text and not a couple of start and end date when available-->
			<xsd:element name="DocumentIssuer" type="toop:DocumentIssuerType" minOccurs="0" maxOccurs="1"/> 
			<xsd:element name="Document" type="toop:DocumentType" minOccurs="0" maxOccurs="unbounded"/> 
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DocumentIssuerType"> 
		<xsd:sequence>
			<xsd:element name="DocumentIssuerIdentifier" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>  
			<xsd:element name="DocumentIssuerName" type="udt:TextType" minOccurs="0" maxOccurs="1"/>  
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DocumentType"> 
		<xsd:sequence>
			<xsd:element name="ExternalDocumentURI" type="udt:IdentifierType" minOccurs="0" maxOccurs="unbounded"/>  
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="DataProviderType">
		<xsd:sequence>
			<xsd:element name="DPIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="DPName" type="udt:TextType"/>
			<xsd:element name="DPAdministrativeUnit" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/> 
			<xsd:element name="DPElectronicAddressIdentifier" type="udt:IdentifierType"/>  
			<xsd:element name="DPLegalAddress" type="toop:AddressType"/>
			<xsd:element name="DPContactDetails" type="toop:ContactDetailsType" minOccurs="0" maxOccurs="1"/> 
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="ContactDetailsType"> 
		<xsd:sequence>
			<xsd:element name="ContactPoint" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>  
			<xsd:element name="ContactTelephoneNumber" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>  
			<xsd:element name="ContactFaxNumber" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>  
			<xsd:element name="ContactEmailAddress" type="udt:IdentifierType" minOccurs="0" maxOccurs="1"/>  
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="NationalOOPServiceProviderType">
		<xsd:sequence>
			<xsd:element name="OOPServiceProviderIdentifier" type="udt:IdentifierType"/>
			<xsd:element name="OOPServiceProviderName" type="udt:TextType"/>
			<xsd:element name="OOPServiceProviderElectronicAddressIdentifier" type="udt:IdentifierType"/>  
			<xsd:element name="OOPServiceProviderCountry" type="udt:TextType"/>
			<xsd:element name="OOPServiceProviderCountryCode" type="udt:CodeType"/> 
		</xsd:sequence>
	</xsd:complexType>
	
	<!--************************************ -->
	<!--RESPONSE specific elements stop here -->
	<!--************************************ -->

	<!-- TOOP specific enumerations and extensions-->

	<xsd:simpleType name="GenderType">
		<xsd:annotation>
			<xsd:documentation> Gender of the natural person. </xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="Male"/>
			<xsd:enumeration value="Female"/>
			<xsd:enumeration value="Other"/>
			<xsd:enumeration value="Unspecified"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="DocumentTypeCodeType">
		<xsd:annotation>
			<xsd:documentation> Identifies if the specific document type is a data request or a data response. The code also identifies the business domain (e.g. registered organization) of the request and response instance. The business domain is related to a set of toop concepts which can be referencend by this document type. </xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="data.request.registeredorganization"/>
			<xsd:enumeration value="data.response.registeredorganization"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="CodeType-TwoUppercaseLetters">
		<xsd:annotation>
			<xsd:documentation> udt:CodeType containing exactly two uppercase letters. </xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="udt:CodeType">
				<xsd:pattern value="[A-Z]{2}" />
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:complexType name="CodeType-FourDigits">
		<xsd:annotation>
			<xsd:documentation> udt:CodeType containing exactly four digits. </xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="udt:CodeType">
				<xsd:pattern value="[0-9]{4}" />
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	
</xsd:schema>

=== TOOP4EU/toop-commons/toop-commons/src/main/resources/xsd/toop/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<toop:TOOP_DataResponse xmlns:ccts="urn:un:unece:uncefact:documentation:2"
 xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2"
 xmlns:toop="http://toop.eu"
 xmlns:udt="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://toop.eu file:/C:/Users/yyi3320.ICNT/Desktop/TOOP_xsd_v0.5/xsd/toop/TOOP_DataExchange.xsd">
    <DocumentIdentifier schemeID="schemeID0" schemeName="schemeName0" schemeAgencyID="schemeAgencyID0" schemeAgencyName="schemeAgencyName0" schemeVersionID="schemeVersionID0" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">DocumentIdentifier0</DocumentIdentifier>
    <DocumentIssueDate>2006-05-04</DocumentIssueDate>
    <DocumentIssueTime>01:01:01.001</DocumentIssueTime>
    <DocumentUniversalUniqueIdentifier schemeID="schemeID1" schemeName="schemeName1" schemeAgencyID="schemeAgencyID1" schemeAgencyName="schemeAgencyName1" schemeVersionID="schemeVersionID1" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">DocumentUniversalUniqueIdentifier0</DocumentUniversalUniqueIdentifier>
    <DocumentVersionIdentifier schemeID="schemeID2" schemeName="schemeName2" schemeAgencyID="schemeAgencyID2" schemeAgencyName="schemeAgencyName2" schemeVersionID="schemeVersionID2" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">DocumentVersionIdentifier0</DocumentVersionIdentifier>
    <CopyIndicator>false</CopyIndicator>
    <DocumentTypeCode>data.request.registeredorganization</DocumentTypeCode>
    <SpecificationIdentifier schemeID="schemeID3" schemeName="schemeName3" schemeAgencyID="schemeAgencyID3" schemeAgencyName="schemeAgencyName3" schemeVersionID="schemeVersionID3" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">SpecificationIdentifier0</SpecificationIdentifier>
    <ProcessIdentifier schemeID="schemeID4" schemeName="schemeName4" schemeAgencyID="schemeAgencyID4" schemeAgencyName="schemeAgencyName4" schemeVersionID="schemeVersionID4" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">ProcessIdentifier0</ProcessIdentifier>
    <SessionIdentifier schemeID="schemeID5" schemeName="schemeName5" schemeAgencyID="schemeAgencyID5" schemeAgencyName="schemeAgencyName5" schemeVersionID="schemeVersionID5" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">SessionIdentifier0</SessionIdentifier>
    <DataConsumer>
        <DCUniqueIdentifier schemeID="schemeID6" schemeName="schemeName6" schemeAgencyID="schemeAgencyID6" schemeAgencyName="schemeAgencyName6" schemeVersionID="schemeVersionID6" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">DCUniqueIdentifier0</DCUniqueIdentifier>
        <DCName languageID="en-US" languageLocaleID="languageLocaleID0">DCName0</DCName>
        <DCElectronicAddressIdentifier schemeID="schemeID7" schemeName="schemeName7" schemeAgencyID="schemeAgencyID7" schemeAgencyName="schemeAgencyName7" schemeVersionID="schemeVersionID7" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">DCElectronicAddressIdentifier0</DCElectronicAddressIdentifier>
        <DCWebsite schemeID="schemeID8" schemeName="schemeName8" schemeAgencyID="schemeAgencyID8" schemeAgencyName="schemeAgencyName8" schemeVersionID="schemeVersionID8" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">DCWebsite0</DCWebsite>
        <DCLegalAddress>
            <AddressLine1 languageID="en-US" languageLocaleID="languageLocaleID1">AddressLine10</AddressLine1>
            <AddressLine2 languageID="en-US" languageLocaleID="languageLocaleID2">AddressLine20</AddressLine2>
            <AddressLine3 languageID="en-US" languageLocaleID="languageLocaleID3">AddressLine30</AddressLine3>
            <StreetName languageID="en-US" languageLocaleID="languageLocaleID4">StreetName0</StreetName>
            <StreetNumber languageID="en-US" languageLocaleID="languageLocaleID5">StreetNumber0</StreetNumber>
            <City languageID="en-US" languageLocaleID="languageLocaleID6">City0</City>
            <PostCode languageID="en-US" languageLocaleID="languageLocaleID7">PostCode0</PostCode>
            <Country languageID="en-US" languageLocaleID="languageLocaleID8">Country0</Country>
            <CountryCode listID="listID0" listAgencyID="listAgencyID0" listAgencyName="listAgencyName0" listName="listName0" listVersionID="listVersionID0" name="name0" languageID="en-US" listURI="http://www.oxygenxml.com/" listSchemeURI="http://www.oxygenxml.com/">AA</CountryCode>
        </DCLegalAddress>
    </DataConsumer>
    <DataSubject>
        <DataSubjectTypeCode listID="listID1" listAgencyID="listAgencyID1" listAgencyName="listAgencyName1" listName="listName1" listVersionID="listVersionID1" name="name1" languageID="en-US" listURI="http://www.oxygenxml.com/" listSchemeURI="http://www.oxygenxml.com/">DataSubjectTypeCode0</DataSubjectTypeCode>
        <LegalEntity>
            <LegalPersonUniqueIdentifier schemeID="schemeID9" schemeName="schemeName9" schemeAgencyID="schemeAgencyID9" schemeAgencyName="schemeAgencyName9" schemeVersionID="schemeVersionID9" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">LegalPersonUniqueIdentifier0</LegalPersonUniqueIdentifier>
            <LegalName languageID="en-US" languageLocaleID="languageLocaleID9">LegalName0</LegalName>
            <VATRegistrationNumber schemeID="schemeID10" schemeName="schemeName10" schemeAgencyID="schemeAgencyID10" schemeAgencyName="schemeAgencyName10" schemeVersionID="schemeVersionID10" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">VATRegistrationNumber0</VATRegistrationNumber>
            <TaxReferenceNumber schemeID="schemeID11" schemeName="schemeName11" schemeAgencyID="schemeAgencyID11" schemeAgencyName="schemeAgencyName11" schemeVersionID="schemeVersionID11" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">TaxReferenceNumber0</TaxReferenceNumber>
            <BusinessCode schemeID="schemeID12" schemeName="schemeName12" schemeAgencyID="schemeAgencyID12" schemeAgencyName="schemeAgencyName12" schemeVersionID="schemeVersionID12" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">BusinessCode0</BusinessCode>
            <LegalEntityIdentifier schemeID="schemeID13" schemeName="schemeName13" schemeAgencyID="schemeAgencyID13" schemeAgencyName="schemeAgencyName13" schemeVersionID="schemeVersionID13" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">LegalEntityIdentifier0</LegalEntityIdentifier>
            <EORIIdentifier schemeID="schemeID14" schemeName="schemeName14" schemeAgencyID="schemeAgencyID14" schemeAgencyName="schemeAgencyName14" schemeVersionID="schemeVersionID14" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">EORIIdentifier0</EORIIdentifier>
            <SEEDIdentifier schemeID="schemeID15" schemeName="schemeName15" schemeAgencyID="schemeAgencyID15" schemeAgencyName="schemeAgencyName15" schemeVersionID="schemeVersionID15" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">SEEDIdentifier0</SEEDIdentifier>
            <StandardIndustrialClassification listID="listID2" listAgencyID="listAgencyID2" listAgencyName="listAgencyName2" listName="listName2" listVersionID="listVersionID2" name="name2" languageID="en-US" listURI="http://www.oxygenxml.com/" listSchemeURI="http://www.oxygenxml.com/">0000</StandardIndustrialClassification>
            <AuthorisedRepresentativeIdentifier schemeID="schemeID16" schemeName="schemeName16" schemeAgencyID="schemeAgencyID16" schemeAgencyName="schemeAgencyName16" schemeVersionID="schemeVersionID16" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">AuthorisedRepresentativeIdentifier0</AuthorisedRepresentativeIdentifier>
            <LegalEntityLegalAddress>
                <AddressLine1 languageID="en-US" languageLocaleID="languageLocaleID10">AddressLine11</AddressLine1>
                <AddressLine2 languageID="en-US" languageLocaleID="languageLocaleID11">AddressLine21</AddressLine2>
                <AddressLine3 languageID="en-US" languageLocaleID="languageLocaleID12">AddressLine31</AddressLine3>
                <StreetName languageID="en-US" languageLocaleID="languageLocaleID13">StreetName1</StreetName>
                <StreetNumber languageID="en-US" languageLocaleID="languageLocaleID14">StreetNumber1</StreetNumber>
                <City languageID="en-US" languageLocaleID="languageLocaleID15">City1</City>
                <PostCode languageID="en-US" languageLocaleID="languageLocaleID16">PostCode1</PostCode>
                <Country languageID="en-US" languageLocaleID="languageLocaleID17">Country1</Country>
                <CountryCode listID="listID3" listAgencyID="listAgencyID3" listAgencyName="listAgencyName3" listName="listName3" listVersionID="listVersionID3" name="name3" languageID="en-US" listURI="http://www.oxygenxml.com/" listSchemeURI="http://www.oxygenxml.com/">AA</CountryCode>
            </LegalEntityLegalAddress>
        </LegalEntity>
        <NaturalPerson>
            <PersonIdentifier schemeID="schemeID17" schemeName="schemeName17" schemeAgencyID="schemeAgencyID17" schemeAgencyName="schemeAgencyName17" schemeVersionID="schemeVersionID17" schemeDataURI="http://www.oxygenxml.com/" schemeURI="http://www.oxygenxml.com/">PersonIdentifier0</PersonIdentifier>
            <FamilyName languageID="en-US" languageLocaleID="languageLocaleID18">FamilyName0</FamilyName>
            <FirstName languageID="en-US" languageLocaleID="languageLocaleID19">FirstName0</FirstName>
            <BirthDate>2006-05-04</BirthDate>
